// Condor roster-code table (Phase 1b): one authoritative table in the airline pack, a generated
// Apps Script copy, and a backend classifier that reads it with byte-identical output.
// The golden file holds BASELINE classifier outputs captured from commit 48d800a (synthetic inputs).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { loadGs, GS_FILES } from './gs-harness.js';
import { CONDOR_ROSTER_CODES, CONDOR_FLIGHT_DESIGNATORS } from '../src/airlines/condor/roster-codes.js';
import { getAirline } from '../src/airlines/index.js';
import { renderCondorCodesGs } from '../scripts/gen-condor-codes-gs.mjs';

const gs = loadGs();
const golden = JSON.parse(readFileSync(new URL('./fixtures/condor-classifier.golden.json', import.meta.url), 'utf8'));
const gsDir = new URL('../backend/apps-script/', import.meta.url);
const classifyWith = (g, input) => g.fcv2ClassifyEvent_(input, g.FCV2_CONDOR_CONFIG_);
const bare = (title) => ({ sourceId: 'x', title, start: 0, end: 1, description: '', basis: 'airline-feed' });

// --- Golden equivalence ---------------------------------------------------------------

test('golden corpus: synthetic, large, and covers every outcome', () => {
  assert.equal(golden._synthetic, true);
  assert.ok(golden.cases.length >= 150, `corpus size ${golden.cases.length}`);
  const kinds = new Set(golden.cases.map((c) => c.output.kind));
  for (const k of ['flight', 'checkin', 'pickup', 'standby', 'reserve', 'off', 'unknown']) assert.ok(kinds.has(k), k);
});

test('the table-driven classifier reproduces every baseline output byte for byte', () => {
  for (const c of golden.cases) {
    assert.equal(JSON.stringify(classifyWith(gs, c.input)), JSON.stringify(c.output), `title ${JSON.stringify(c.input.title)}`);
  }
});

// --- Generated Apps Script copy -------------------------------------------------------

test('CondorCodesV2.gs is exactly the generated copy of the pack table', () => {
  const file = readFileSync(new URL('CondorCodesV2.gs', gsDir), 'utf8');
  assert.equal(file, renderCondorCodesGs());
  assert.match(file, /^\/\/ GENERATED by scripts\/gen-condor-codes-gs\.mjs .* Do not edit by hand\./);
});

test('the sandbox global equals the pack table, deeply frozen', () => {
  assert.deepEqual(JSON.parse(JSON.stringify(gs.FCV2_CONDOR_CODES_)), { flightDesignators: CONDOR_FLIGHT_DESIGNATORS, codes: CONDOR_ROSTER_CODES });
  assert.ok(Object.isFrozen(gs.FCV2_CONDOR_CODES_) && Object.isFrozen(gs.FCV2_CONDOR_CODES_.codes) && Object.isFrozen(gs.FCV2_CONDOR_CODES_.codes[0].match));
  assert.equal('airlineCodes' in gs.FCV2_CONDOR_CONFIG_, false, 'the adapter config no longer duplicates designators');
  assert.equal('dayCodes' in gs.FCV2_CONDOR_CONFIG_, false, 'the adapter config no longer duplicates day codes');
});

// --- Load order (Apps Script appends a new file last) ---------------------------------

function loadOrdered(files) {
  const sandbox = { console };
  vm.createContext(sandbox);
  const code = files.map((f) => readFileSync(new URL(f, gsDir), 'utf8')).join('\n;\n');
  vm.runInContext(`${code}\n;globalThis.__g = { fcv2ClassifyEvent_, FCV2_CONDOR_CONFIG_ };`, sandbox);
  return sandbox.__g;
}
const BACKEND = GS_FILES.filter((f) => f !== 'CondorCodesV2.gs');

test('load order: the codes file may come first or last; the adapter alone loads without it', () => {
  const sample = golden.cases.filter((_, i) => i % 7 === 0);
  for (const order of [['CondorCodesV2.gs', ...BACKEND], [...BACKEND, 'CondorCodesV2.gs']]) {
    const g = loadOrdered(order);
    for (const c of sample) assert.equal(JSON.stringify(classifyWith(g, c.input)), JSON.stringify(c.output), order[0]);
  }
  // Adapter before codes is the production order; with no codes file at all nothing throws at load time.
  assert.doesNotThrow(() => loadOrdered(['CondorAdapterV2.gs', 'CondorCodesV2.gs']));
  assert.doesNotThrow(() => loadOrdered(['CondorAdapterV2.gs']));
  const adapter = readFileSync(new URL('CondorAdapterV2.gs', gsDir), 'utf8');
  const topLevel = adapter.split('\n').filter((l) => /^(const|let|var) /.test(l)).join('\n');
  assert.doesNotMatch(topLevel, /FCV2_CONDOR_CODES_/, 'no top-level declaration reads the codes file');
});

// --- Table shape ----------------------------------------------------------------------

test('the table holds only typedef fields and contract-v2 canonical values', () => {
  const FIELDS = new Set(['id', 'match', 'kind', 'subtype', 'protected', 'source']);
  const KINDS = new Set(['checkin', 'pickup', 'standby', 'reserve', 'off']);
  const SUBTYPES = new Set(['off', 'free', 'leave', 'ort']);
  assert.deepEqual(CONDOR_ROSTER_CODES.map((d) => d.id), ['checkin', 'pickup', 'standby-sb', 'reserve-re', 'day-off', 'day-free', 'day-leave', 'day-ort']);
  assert.equal(new Set(CONDOR_ROSTER_CODES.map((d) => d.id)).size, CONDOR_ROSTER_CODES.length, 'ids are unique');
  for (const d of CONDOR_ROSTER_CODES) {
    for (const k of Object.keys(d)) assert.ok(FIELDS.has(k), `${d.id}: unexpected field ${k}`);
    assert.ok(KINDS.has(d.kind), `${d.id}: kind ${d.kind}`);
    if ('subtype' in d) assert.ok(SUBTYPES.has(d.subtype), `${d.id}: subtype ${d.subtype}`);
    assert.equal(d.kind === 'off', 'subtype' in d, `${d.id}: only free-family codes carry a subtype`);
    if ('protected' in d) assert.equal(d.protected, true);
    assert.deepEqual(Object.keys(d.match).length, 1);
    const [type, value] = Object.entries(d.match)[0];
    assert.ok(type === 'exact' || type === 'pattern');
    assert.ok(typeof value === 'string' && value.length > 0);
    if (type === 'pattern') assert.match(value, /^\^.*\$$/, `${d.id}: pattern is anchored`);
    assert.match(d.source, /^docs\/CONTRACT-V2\.md /);
    assert.ok(Object.isFrozen(d) && Object.isFrozen(d.match));
  }
  assert.ok(Object.isFrozen(CONDOR_ROSTER_CODES) && Object.isFrozen(CONDOR_FLIGHT_DESIGNATORS));
  assert.deepEqual([...CONDOR_FLIGHT_DESIGNATORS], ['DE']);
  assert.equal(CONDOR_ROSTER_CODES.filter((d) => d.protected).map((d) => d.id).join(), 'day-ort');
});

test('the Condor pack exposes the table; terminology stays separate from raw codes', () => {
  const condor = getAirline('condor');
  assert.equal(condor.rosterCodes, CONDOR_ROSTER_CODES);
  assert.equal(condor.flightDesignators, CONDOR_FLIGHT_DESIGNATORS);
  assert.equal(getAirline('generic').rosterCodes, undefined);
  assert.doesNotMatch(JSON.stringify(CONDOR_ROSTER_CODES), /Protected free day|Off day|Free day|label/);
});

// --- Phase 1b changed no behaviour ----------------------------------------------------

test('unrecognised Fibel symbols and agreement names are still unknown', () => {
  for (const t of ['--', 'SB90S', 'SB90_I', 'SBH30', 'SBAUS', 'SB90KO', 'SBY', 'SBYHOT', 'SBYKO', 'SB30-AUS', 'SBYAP', 'RES10', 'RES10_I', 'SB1000', 'sb90', 'SB 90']) {
    for (const title of [t, `✈️✈️✈️ ${t}`]) {
      const e = classifyWith(gs, bare(title));
      assert.equal(e.kind, 'unknown', title);
      assert.equal(e.subtype, null, title);
      assert.equal(e.protected, false, title);
      assert.equal(e.hotel, null, title);
    }
  }
});

test('own-key semantics: prototype names are never codes', () => {
  for (const t of ['__proto__', 'toString', 'constructor', 'hasOwnProperty', 'valueOf']) assert.equal(classifyWith(gs, bare(t)).kind, 'unknown', t);
});

test('every recognised code in the corpus maps to exactly one table entry, and every entry is exercised', () => {
  const tests = CONDOR_ROSTER_CODES.map((d) => ('exact' in d.match ? (t) => t === d.match.exact : (t) => new RegExp(d.match.pattern).test(t)));
  const used = new Set();
  for (const c of golden.cases) {
    const o = c.output;
    if (o.kind === 'flight' || o.kind === 'unknown') {
      if (o.kind === 'unknown') assert.ok(!tests.some((t) => t(o.title)), `unknown title ${JSON.stringify(o.title)} matches no entry`);
      continue;
    }
    const hits = CONDOR_ROSTER_CODES.filter((_, i) => tests[i](o.title));
    assert.equal(hits.length, 1, `${JSON.stringify(o.title)} matches ${hits.length} entries`);
    const d = hits[0];
    assert.deepEqual([o.kind, o.subtype, o.protected], [d.kind, d.subtype ?? null, d.protected === true], o.title);
    used.add(d.id);
  }
  assert.deepEqual([...used].sort(), CONDOR_ROSTER_CODES.map((d) => d.id).sort());
});
