// GENERATED by scripts/gen-condor-codes-gs.mjs from src/airlines/condor/roster-codes.js. Do not edit by hand.
// Condor roster codes: raw feed title → canonical Flight Control concept (contract v2), in match
// order (first match wins). `exact` compares the cleaned title; `pattern` is an anchored regex
// source. Read by fcv2ClassifyEvent_ at call time only (this file loads after CondorAdapterV2.gs).
const FCV2_CONDOR_CODES_ = Object.freeze({
  flightDesignators: Object.freeze(["DE"]),
  codes: Object.freeze([
    Object.freeze({ id: "checkin", match: Object.freeze({ exact: "C/I" }), kind: "checkin", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "pickup", match: Object.freeze({ exact: "P/U" }), kind: "pickup", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "standby-sb", match: Object.freeze({ pattern: "^SB\\d{0,3}$" }), kind: "standby", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "reserve-re", match: Object.freeze({ pattern: "^RE\\d{0,3}$" }), kind: "reserve", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "day-off", match: Object.freeze({ exact: "OFF" }), kind: "off", subtype: "off", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "day-free", match: Object.freeze({ exact: "-" }), kind: "off", subtype: "free", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "day-leave", match: Object.freeze({ exact: "U" }), kind: "off", subtype: "leave", source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "day-ort", match: Object.freeze({ exact: "ORT" }), kind: "off", subtype: "ort", protected: true, source: "docs/CONTRACT-V2.md source inventory (2026-10-04)" }),
    Object.freeze({ id: "day-unassigned", match: Object.freeze({ exact: "--" }), kind: "unassigned", source: "Condor MTV Fibel p.10 (Strichtage \"--\"); owner decision 2026-10-06" }),
    Object.freeze({ id: "standby-sb90s", match: Object.freeze({ exact: "SB90S" }), kind: "standby", source: "Condor MTV Fibel (Verdi) p.17, Symbol Dienstplan" }),
    Object.freeze({ id: "standby-sb90-i", match: Object.freeze({ exact: "SB90_I" }), kind: "standby", source: "Condor MTV Fibel (Verdi) p.17, Symbol Dienstplan" }),
    Object.freeze({ id: "standby-sbh30", match: Object.freeze({ exact: "SBH30" }), kind: "standby", source: "Condor MTV Fibel (Verdi) p.17, Symbol Dienstplan" }),
    Object.freeze({ id: "standby-sbaus", match: Object.freeze({ exact: "SBAUS" }), kind: "standby", source: "Condor MTV Fibel (Verdi) p.17, Symbol Dienstplan" }),
    Object.freeze({ id: "standby-sb90ko", match: Object.freeze({ exact: "SB90KO" }), kind: "standby", source: "Condor MTV Fibel (Verdi) p.17, Symbol Dienstplan" }),
  ]),
});
